sensor:
  - platform: template
    sensors:
      sunelevation:
        entity_id: sun.sun
        friendly_name: 'Sun Elevation'
        value_template: >
          {{ states.sun.sun.attributes.elevation if states.sun.sun.attributes.elevation > 0 else 'Below the horizon' }}
      nextsunrise:
        entity_id: sun.sun
        friendly_name: 'Next Sunrise'
        value_template: >
          {{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom(' %I:%M %p') | replace(" 0", "") }}
        icon_template: mdi:weather-sunset-up
      nextsunset:
        entity_id: sun.sun
        friendly_name: 'Next Sunset'
        value_template: >
          {{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom(' %I:%M %p') | replace(" 0", "") }}
        icon_template: mdi:weather-sunset-down
      moon_phases:
        entity_id: sensor.moon
        friendly_name: 'Moon Phase'
        value_template: >-
          {% if is_state('sensor.moon', 'new_moon') %}
          New Moon
          {% elif is_state('sensor.moon', 'waxing_crescent') %}
          Waxing Crescent
          {% elif is_state('sensor.moon', 'first_quarter') %}
          First Quarter
          {% elif is_state('sensor.moon', 'waxing_gibbous') %}
          Waxing Gibbous
          {% elif is_state('sensor.moon', 'full_moon') %}
          Full Moon
          {% elif is_state('sensor.moon', 'waning_gibbous') %}
          Waning Gibbous
          {% elif is_state('sensor.moon', 'last_quarter') %}
          Last Quarter
          {% elif is_state('sensor.moon', 'waning_crescent') %}
          Waning Crescent
          {% endif %}
        icon_template: >-
          {% if is_state('sensor.moon', 'new_moon') %}
          mdi:moon-new
          {% elif is_state('sensor.moon', 'waxing_crescent') %}
          mdi:moon-waxing-crescent
          {% elif is_state('sensor.moon', 'first_quarter') %}
          mdi:moon-first-quarter
          {% elif is_state('sensor.moon', 'waxing_gibbous') %}
          mdi:moon-waxing-gibbous
          {% elif is_state('sensor.moon', 'full_moon') %}
          mdi:moon-full
          {% elif is_state('sensor.moon', 'waning_gibbous') %}
          mdi:waning-gibbous
          {% elif is_state('sensor.moon', 'last_quarter') %}
          mdi:moon-last-quarter
          {% elif is_state('sensor.moon', 'waning_crescent') %}
          mdi:moon-waning-crescent
          {% endif %}
      smoke_co:
        friendly_name: "Smoke/CO - Status"
        value_template: >-
          {%- if is_state("sensor.first_alert_brk_brands_inc_zcombo_smoke_and_carbon_monoxide_detector_alarm_level", "0") %}
            Idle
          {%- else %}
            {%- if is_state("sensor.first_alert_brk_brands_inc_zcombo_smoke_and_carbon_monoxide_detector_alarm_type", "1") %}
              Fire
            {%- elif is_state("sensor.first_alert_brk_brands_inc_zcombo_smoke_and_carbon_monoxide_detector_alarm_type", "2") %}
              CO
            {%- elif is_state("sensor.first_alert_brk_brands_inc_zcombo_smoke_and_carbon_monoxide_detector_alarm_type", "12") %}
              Testing
            {%- elif is_state("sensor.first_alert_brk_brands_inc_zcombo_smoke_and_carbon_monoxide_detector_alarm_type", "13") %}
              Idle
            {% else %}
              Unknown
            {%- endif %}
          {%- endif %}
        entity_id: sensor.first_alert_brk_brands_inc_zcombo_smoke_and_carbon_monoxide_detector_alarm_level
